# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='postoffice.proto',
  package='',
  serialized_pb='\n\x10postoffice.proto\"+\n\x0c\x42oxContainer\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\")\n\x16UsercacheLookupRequest\x12\x0f\n\x07user_id\x18\x03 \x03(\t\"r\n\x17UsercacheLookupResponse\x12+\n\x04user\x18\x03 \x03(\x0b\x32\x1d.UsercacheLookupResponse.User\x1a*\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04')




_BOXCONTAINER = descriptor.Descriptor(
  name='BoxContainer',
  full_name='BoxContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='BoxContainer.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='BoxContainer.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=63,
)


_USERCACHELOOKUPREQUEST = descriptor.Descriptor(
  name='UsercacheLookupRequest',
  full_name='UsercacheLookupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='UsercacheLookupRequest.user_id', index=0,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=106,
)


_USERCACHELOOKUPRESPONSE_USER = descriptor.Descriptor(
  name='User',
  full_name='UsercacheLookupResponse.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='UsercacheLookupResponse.User.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='UsercacheLookupResponse.User.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=180,
  serialized_end=222,
)

_USERCACHELOOKUPRESPONSE = descriptor.Descriptor(
  name='UsercacheLookupResponse',
  full_name='UsercacheLookupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='UsercacheLookupResponse.user', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERCACHELOOKUPRESPONSE_USER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=108,
  serialized_end=222,
)

_USERCACHELOOKUPRESPONSE_USER.containing_type = _USERCACHELOOKUPRESPONSE;
_USERCACHELOOKUPRESPONSE.fields_by_name['user'].message_type = _USERCACHELOOKUPRESPONSE_USER
DESCRIPTOR.message_types_by_name['BoxContainer'] = _BOXCONTAINER
DESCRIPTOR.message_types_by_name['UsercacheLookupRequest'] = _USERCACHELOOKUPREQUEST
DESCRIPTOR.message_types_by_name['UsercacheLookupResponse'] = _USERCACHELOOKUPRESPONSE

class BoxContainer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOXCONTAINER
  
  # @@protoc_insertion_point(class_scope:BoxContainer)

class UsercacheLookupRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERCACHELOOKUPREQUEST
  
  # @@protoc_insertion_point(class_scope:UsercacheLookupRequest)

class UsercacheLookupResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class User(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERCACHELOOKUPRESPONSE_USER
    
    # @@protoc_insertion_point(class_scope:UsercacheLookupResponse.User)
  DESCRIPTOR = _USERCACHELOOKUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:UsercacheLookupResponse)

# @@protoc_insertion_point(module_scope)
