# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='postoffice.proto',
  package='',
  serialized_pb='\n\x10postoffice.proto\"+\n\x0c\x42oxContainer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x0c\")\n\x16UsercacheLookupRequest\x12\x0f\n\x07user_id\x18\x03 \x03(\t\"\x82\x01\n\x17UsercacheLookupResponse\x12+\n\x04user\x18\x03 \x03(\x0b\x32\x1d.UsercacheLookupResponse.User\x1a:\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xb3\x01\n\x12SendMessageRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x13\n\x0boriginal_id\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x02(\t\x12\x11\n\trecipient\x18\x04 \x02(\t\x12\r\n\x05group\x18\x05 \x01(\t\x12\x0c\n\x04mime\x18\x06 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x02(\x0c\x12\x11\n\tencrypted\x18\x08 \x01(\x08\x12\x0b\n\x03url\x18\t \x01(\t\x12\x0b\n\x03ttl\x18\n \x02(\r\".\n\x13SendMessageResponse\x12\x17\n\x06status\x18\x01 \x02(\x0e\x32\x07.Status\"&\n\x13MessageQueueRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"-\n\x14MessageQueueResponse\x12\x15\n\rmessage_count\x18\x01 \x02(\r*\xcf\x01\n\x06Status\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01\x12\x0f\n\x0bSTATUS_BUSY\x10\x02\x12\x1e\n\x1aSTATUS_VERIFICATION_FAILED\x10\x03\x12\x1f\n\x1bSTATUS_INVALID_PHONE_NUMBER\x10\x04\x12\x16\n\x12STATUS_TTL_EXPIRED\x10\x05\x12\x18\n\x14STATUS_USER_NOTFOUND\x10\x06\x12\x1b\n\x17STATUS_MESSAGE_NOTFOUND\x10\x07')

_STATUS = descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_ERROR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_BUSY', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_VERIFICATION_FAILED', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_PHONE_NUMBER', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_TTL_EXPIRED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_USER_NOTFOUND', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_MESSAGE_NOTFOUND', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=559,
  serialized_end=766,
)


STATUS_SUCCESS = 0
STATUS_ERROR = 1
STATUS_BUSY = 2
STATUS_VERIFICATION_FAILED = 3
STATUS_INVALID_PHONE_NUMBER = 4
STATUS_TTL_EXPIRED = 5
STATUS_USER_NOTFOUND = 6
STATUS_MESSAGE_NOTFOUND = 7



_BOXCONTAINER = descriptor.Descriptor(
  name='BoxContainer',
  full_name='BoxContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='BoxContainer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='BoxContainer.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=63,
)


_USERCACHELOOKUPREQUEST = descriptor.Descriptor(
  name='UsercacheLookupRequest',
  full_name='UsercacheLookupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='UsercacheLookupRequest.user_id', index=0,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=106,
)


_USERCACHELOOKUPRESPONSE_USER = descriptor.Descriptor(
  name='User',
  full_name='UsercacheLookupResponse.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='UsercacheLookupResponse.User.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='UsercacheLookupResponse.User.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='UsercacheLookupResponse.User.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=181,
  serialized_end=239,
)

_USERCACHELOOKUPRESPONSE = descriptor.Descriptor(
  name='UsercacheLookupResponse',
  full_name='UsercacheLookupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='UsercacheLookupResponse.user', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERCACHELOOKUPRESPONSE_USER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=239,
)


_SENDMESSAGEREQUEST = descriptor.Descriptor(
  name='SendMessageRequest',
  full_name='SendMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='SendMessageRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='original_id', full_name='SendMessageRequest.original_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sender', full_name='SendMessageRequest.sender', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recipient', full_name='SendMessageRequest.recipient', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='SendMessageRequest.group', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mime', full_name='SendMessageRequest.mime', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='SendMessageRequest.content', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypted', full_name='SendMessageRequest.encrypted', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='SendMessageRequest.url', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ttl', full_name='SendMessageRequest.ttl', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=242,
  serialized_end=421,
)


_SENDMESSAGERESPONSE = descriptor.Descriptor(
  name='SendMessageResponse',
  full_name='SendMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='SendMessageResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=469,
)


_MESSAGEQUEUEREQUEST = descriptor.Descriptor(
  name='MessageQueueRequest',
  full_name='MessageQueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MessageQueueRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=471,
  serialized_end=509,
)


_MESSAGEQUEUERESPONSE = descriptor.Descriptor(
  name='MessageQueueResponse',
  full_name='MessageQueueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_count', full_name='MessageQueueResponse.message_count', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=556,
)

_USERCACHELOOKUPRESPONSE_USER.containing_type = _USERCACHELOOKUPRESPONSE;
_USERCACHELOOKUPRESPONSE.fields_by_name['user'].message_type = _USERCACHELOOKUPRESPONSE_USER
_SENDMESSAGERESPONSE.fields_by_name['status'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['BoxContainer'] = _BOXCONTAINER
DESCRIPTOR.message_types_by_name['UsercacheLookupRequest'] = _USERCACHELOOKUPREQUEST
DESCRIPTOR.message_types_by_name['UsercacheLookupResponse'] = _USERCACHELOOKUPRESPONSE
DESCRIPTOR.message_types_by_name['SendMessageRequest'] = _SENDMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['SendMessageResponse'] = _SENDMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['MessageQueueRequest'] = _MESSAGEQUEUEREQUEST
DESCRIPTOR.message_types_by_name['MessageQueueResponse'] = _MESSAGEQUEUERESPONSE

class BoxContainer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOXCONTAINER
  
  # @@protoc_insertion_point(class_scope:BoxContainer)

class UsercacheLookupRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERCACHELOOKUPREQUEST
  
  # @@protoc_insertion_point(class_scope:UsercacheLookupRequest)

class UsercacheLookupResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class User(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERCACHELOOKUPRESPONSE_USER
    
    # @@protoc_insertion_point(class_scope:UsercacheLookupResponse.User)
  DESCRIPTOR = _USERCACHELOOKUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:UsercacheLookupResponse)

class SendMessageRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDMESSAGEREQUEST
  
  # @@protoc_insertion_point(class_scope:SendMessageRequest)

class SendMessageResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDMESSAGERESPONSE
  
  # @@protoc_insertion_point(class_scope:SendMessageResponse)

class MessageQueueRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEQUEUEREQUEST
  
  # @@protoc_insertion_point(class_scope:MessageQueueRequest)

class MessageQueueResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEQUEUERESPONSE
  
  # @@protoc_insertion_point(class_scope:MessageQueueResponse)

# @@protoc_insertion_point(module_scope)
